[package]
name = "payments_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.51"
csv = "1.4.0"
rust_decimal = { version = "1.39.0", features = ["macros"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
